import { Check } from "lucide-react";
import React, { useState } from "react";
import PlanCard from "./plan-cards";
import ReceiptIcon from "../atoms/receipt-icon";
import { useRouter } from "next/navigation";

export const Date = [
	{ id: 1, title: 2024 },
	{ id: 2, title: 2023 },
	{ id: 3, title: 2022 },
	{ id: 4, title: 2021 },
	{ id: 5, title: 2020 },
	{ id: 6, title: 2019 },
	{ id: 7, title: 2018 },
	{ id: 8, title: 2017 },
	{ id: 9, title: 2016 },
	{ id: 10, title: 2015 },
];

const PricingCards = () => {
	const [activeYears, setActiveYears] = useState<number[]>([2022]);

	// Toggle year selection
	const toggleYear = (year: number) => {
		setActiveYears((prev) =>
			prev.includes(year) ? prev.filter((y) => y !== year) : [...prev, year]
		);
	};

	return (
		<div className='w-full lg:min-h-[400px] h-fit space-y-[32px] lg:space-y-[10px]'>
			<h5 className='font-bold text-2xl'>Select your tax year(s)</h5>
			<p className='text-grey-600'>
				You can choose to buy a plan for one assessment year or multiple years.
				10%* discount for multiple years purchase.
			</p>
			<div className='flex w-full pb-5 gap-2 flex-wrap'>
				{Date.map(({ id, title }) => (
					<div
						key={id}
						onClick={() => toggleYear(title)}
						className={`rounded-full py-2 px-4 text-sm cursor-pointer transition-all duration-200 transform ${
							activeYears.includes(title)
								? "text-secondary bg-destructive-foreground scale-105"
								: "bg-[#E5EBEF] text-black hover:bg-gray-300"
						}`}
					>
						{title}
					</div>
				))}
			</div>
			<div className='w-full space-y-[32px]'>
				<div className='w-full h-full grid grid-cols-1 lg:grid-cols-4 gap-10'>
					{/* Basic */}
					<PlanCard
						amount='75'
						pack='Starter pack'
						title='Basic'
						current={true} // Mark this plan as the current plan
						pecks={
							<ul className='space-y-4'>
								<li className='flex items-start gap-2 text-sm text-[hsla(215,16%,47%,1)]'>
									<Check className='h-5 w-5 text-secondary mt-0.5' />
									<span className='text-sm'>
										Up to <span className='font-semibold'>1,000</span>{" "}
										Transactions
									</span>
								</li>
								<li className='flex items-start gap-2 text-sm text-[hsla(215,16%,47%,1)]'>
									<Check className='h-5 w-5 text-secondary mt-0.5' />
									<span className='text-sm'>
										Autogenerated Tax forms of designated country
									</span>
								</li>
							</ul>
						}
					/>

					{/* Premium */}
					<PlanCard
						amount='350'
						pack='Advanced, recommended'
						title='Premium'
						pecks={
							<ul className='space-y-4'>
								<li className='flex items-start gap-2 text-sm text-[hsla(215,16%,47%,1)]'>
									<Check className='h-5 w-5 text-secondary mt-0.5' />
									<span className='text-sm'>
										Up to <span className='font-semibold'>8,000</span>{" "}
										Transactions
									</span>
								</li>
								<li className='flex items-start gap-2 text-sm text-[hsla(215,16%,47%,1)]'>
									<Check className='h-5 w-5 text-secondary mt-0.5' />
									<span className='text-sm'>
										Autogenerated Tax forms of designated country
									</span>
								</li>
							</ul>
						}
					/>

					{/* Customized */}
					<PlanCard
						amount='***'
						pack='Unlimited plan'
						title='Customized'
						customized={true}
						pecks={
							<ul className='space-y-4'>
								<li className='flex items-start gap-2 text-sm text-[hsla(215,16%,47%,1)]'>
									<Check className='h-5 w-5 text-secondary mt-0.5' />
									<span className='text-sm'>
										<span className='font-semibold'>Unlimited</span>{" "}
										Transactions
									</span>
								</li>
								<li className='flex items-start gap-2 text-sm text-[hsla(215,16%,47%,1)]'>
									<Check className='h-5 w-5 text-secondary mt-0.5' />
									<span className='text-sm'>
										Autogenerated Tax forms of designated country
									</span>
								</li>
							</ul>
						}
					/>

					<div className='bg-[#EBEFF3] shadow-md border rounded-md px-6 py-5'>
						<div className='flex gap-2 items-center border-b border-b-border pb-3'>
							<div className='bg-secondary p-1 rounded-full'>
								<ReceiptIcon className='text-white' />
							</div>
							<h6 className='font-sen font-bold'>Inclusive in all plans</h6>
						</div>
						<ul className='space-y-4 pt-3'>
							<li className='flex items-start gap-2 text-sm text-[hsla(215,16%,47%,1)]'>
								<Check className='h-5 w-5 text-secondary mt-0.5' />
								<span className='text-sm'>Basic Portfolio Tracking</span>
							</li>
							<li className='flex items-start gap-2 text-sm text-[hsla(215,16%,47%,1)]'>
								<Check className='h-5 w-5 text-secondary mt-0.5' />
								<span className='text-sm'>Email Support</span>
							</li>
							<li className='flex items-start gap-2 text-sm text-[hsla(215,16%,47%,1)]'>
								<Check className='h-5 w-5 text-secondary mt-0.5' />
								<span className='text-sm'>CSV Uploads</span>
							</li>
							<li className='flex items-start gap-2 text-sm text-[hsla(215,16%,47%,1)]'>
								<Check className='min-h-5 min-w-5 text-secondary mt-0.5' />
								<span className='text-sm'>
									Unlimited Synchronization of Exchanges, Wallets, Defi, NFT &
									Staking Platforms
								</span>
							</li>
							<li className='flex items-start gap-2 text-sm text-[hsla(215,16%,47%,1)]'>
								<Check className='h-5 w-5 text-secondary mt-0.5' />
								<span className='text-sm'>Manual Transaction Entry</span>
							</li>
							<li className='flex items-start gap-2 text-sm text-[hsla(215,16%,47%,1)]'>
								<Check className='h-5 w-5 text-secondary mt-0.5' />
								<span className='text-sm'>Tax Calculation Type Selection</span>
							</li>
							<li className='flex items-start gap-2 text-sm text-[hsla(215,16%,47%,1)]'>
								<Check className='h-5 w-5 text-secondary mt-0.5' />
								<span className='text-sm'>
									Social Media channels consultation support
								</span>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	);
};

export default PricingCards;
